spring:
  application:
    name: MediQueue

  datasource:
    url: jdbc:postgresql://localhost:5432/medi_queue
    username: postgres
    password: 2003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: j40064535@gmail.com
    password: hxyy goft qjbl yeul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


