spring:
  application:
    name: MediQueue

  mail:
    host: smtp.gmail.com
    port: 587
    username: j40064535@gmail.com
    password: hxyy goft qjbl yeul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


msg91:
  auth-key: 553059AGZuFj7x6a60d79aP1
  template-id: 6a60d6491ddc86f5e508bec3
